import type { SupabaseClient } from "@supabase/supabase-js";
import { toCsv } from "@/export/csv-format";

function boolStr(v: boolean): string {
  return v ? "True" : "False";
}

const HEADER = [
  "Name",
  "Status",
  "Currency",
  "PaymentTerm",
  "TaxRule",
  "AccountReceivable",
  "SaleAccount",
  "PriceTier",
  "Discount",
  "CreditLimit",
  "Carrier",
  "SalesRepresentative",
  "Location",
  "TaxNumber",
  "Tags",
  "DisplayName",
  "IsLegalEntity",
  "ParentCustomer",
  "IsBillParent",
  "AttributeSet",
  "AdditionalAttribute1",
  "AdditionalAttribute2",
  "AdditionalAttribute3",
  "AdditionalAttribute4",
  "AdditionalAttribute5",
  "AdditionalAttribute6",
  "AdditionalAttribute7",
  "AdditionalAttribute8",
  "AdditionalAttribute9",
  "AdditionalAttribute10",
  "Comments",
  "ContactName",
  "JobTitle",
  "Phone",
  "MobilePhone",
  "Fax",
  "Email",
  "Website",
  "ContactComment",
  "ContactDefault",
  "ContactIncludeInEmail",
  "MarketingConsent",
  "IsAccountingDimensionEnabled",
  "DimensionAttribute1",
  "DimensionAttribute2",
  "DimensionAttribute3",
  "DimensionAttribute4",
  "DimensionAttribute5",
  "DimensionAttribute6",
  "DimensionAttribute7",
  "DimensionAttribute8",
  "DimensionAttribute9",
  "DimensionAttribute10",
];

/** Exports the org's canonical customers in the same column format as Cin7's Customers CSV template. */
export async function exportCustomersCsv(db: SupabaseClient, orgId: string): Promise<string> {
  const { data, error } = await db.from("customers").select("*").eq("org_id", orgId).order("name");
  if (error) throw new Error(`customers: ${error.message}`);

  const rows = (data ?? []).map((c) => [
    c.name,
    c.status ?? "",
    c.currency ?? "",
    c.payment_term ?? "",
    c.tax_rule ?? "",
    c.account_receivable ?? "",
    c.sale_account ?? "",
    c.price_tier ?? "",
    c.discount ?? "",
    c.credit_limit ?? "",
    c.carrier ?? "",
    c.sales_representative ?? "",
    c.location ?? "",
    c.tax_number ?? "",
    c.tags ?? "",
    c.display_name ?? "",
    boolStr(c.is_legal_entity),
    c.parent_customer ?? "",
    boolStr(c.is_bill_parent),
    c.attribute_set ?? "",
    c.additional_attribute_1 ?? "",
    c.additional_attribute_2 ?? "",
    c.additional_attribute_3 ?? "",
    c.additional_attribute_4 ?? "",
    c.additional_attribute_5 ?? "",
    c.additional_attribute_6 ?? "",
    c.additional_attribute_7 ?? "",
    c.additional_attribute_8 ?? "",
    c.additional_attribute_9 ?? "",
    c.additional_attribute_10 ?? "",
    c.comments ?? "",
    c.contact_name ?? "",
    c.job_title ?? "",
    c.phone ?? "",
    c.mobile_phone ?? "",
    c.fax ?? "",
    c.email ?? "",
    c.website ?? "",
    c.contact_comment ?? "",
    boolStr(c.contact_default),
    boolStr(c.contact_include_in_email),
    c.marketing_consent ?? "",
    boolStr(c.is_accounting_dimension_enabled),
    c.dimension_attribute_1 ?? "",
    c.dimension_attribute_2 ?? "",
    c.dimension_attribute_3 ?? "",
    c.dimension_attribute_4 ?? "",
    c.dimension_attribute_5 ?? "",
    c.dimension_attribute_6 ?? "",
    c.dimension_attribute_7 ?? "",
    c.dimension_attribute_8 ?? "",
    c.dimension_attribute_9 ?? "",
    c.dimension_attribute_10 ?? "",
  ]);

  return toCsv([HEADER, ...rows]);
}
