-- Customer Reference (Cin7's own field: "Reference number used by customer
-- to identify this sale. Could be a purchase order number generated by
-- customer.") — confirmed via Cin7's own API reference docs 2026-07-10,
-- on the Sale detail resource alongside Note/COGSAmount (detail-only
-- fields, not on the cheap /saleList scan), so extracted from the SAME
-- /sale?ID= call sync-sales.ts's detail phase already makes — no new Cin7
-- calls. Surfaced on the Order Fulfillment report and, in particular, the
-- Fulfillment Cleanup Helper's per-sale exclusion checklist, where a
-- customer's own PO number is often the clearest way to recognize which
-- order to exclude.

alter table sales add column if not exists customer_reference text;

drop function if exists report_order_fulfillment(uuid, uuid[]);

create function report_order_fulfillment(
  p_org_id uuid,
  p_instance_ids uuid[] default null
)
returns table (
  cin7_sale_id text,
  instance_id uuid,
  order_number text,
  customer_name text,
  customer_reference text,
  order_date date,
  days_open integer,
  ship_by date,
  is_overdue boolean,
  order_status text,
  combined_picking_status text,
  combined_packing_status text,
  combined_shipping_status text,
  combined_invoice_status text,
  combined_payment_status text,
  paid_amount numeric,
  invoice_amount numeric,
  total_ordered_qty numeric,
  total_backorder_qty numeric,
  total_pickable_qty numeric,
  total_picked_qty numeric,
  is_pick_today boolean,
  is_ship_today boolean
) language sql stable set search_path = public as $$
  with totals as (
    select
      cin7_sale_id,
      sum(ordered_qty) as total_ordered_qty,
      sum(backorder_qty) as total_backorder_qty,
      sum(pickable_qty) as total_pickable_qty,
      sum(picked_qty) as total_picked_qty
    from report_order_fulfillment_lines(p_org_id, p_instance_ids)
    group by cin7_sale_id
  )
  select
    s.cin7_sale_id,
    s.instance_id,
    s.order_number,
    s.customer_name,
    s.customer_reference,
    s.order_date,
    case when s.order_date is not null then (current_date - s.order_date) end as days_open,
    s.ship_by,
    (s.ship_by is not null and s.ship_by < current_date) as is_overdue,
    s.order_status,
    s.combined_picking_status,
    s.combined_packing_status,
    s.combined_shipping_status,
    s.combined_invoice_status,
    s.combined_payment_status,
    s.paid_amount,
    s.invoice_amount,
    coalesce(t.total_ordered_qty, 0) as total_ordered_qty,
    coalesce(t.total_backorder_qty, 0) as total_backorder_qty,
    coalesce(t.total_pickable_qty, 0) as total_pickable_qty,
    coalesce(t.total_picked_qty, 0) as total_picked_qty,
    coalesce(s.combined_picking_status not in ('PICKED', 'VOIDED', 'NOT AVAILABLE'), false) and coalesce(t.total_pickable_qty, 0) > 0 as is_pick_today,
    coalesce(s.combined_shipping_status not in ('SHIPPED', 'VOIDED', 'NOT AVAILABLE'), false) as is_ship_today
  from sales s
  left join totals t on t.cin7_sale_id = s.cin7_sale_id
  where s.org_id = p_org_id
    and (p_instance_ids is null or s.instance_id = any (p_instance_ids))
  order by (s.ship_by is null) asc, s.ship_by asc;
$$;
